//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSouls
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.invoices = new HashSet<invoices>();
            this.employee1 = new HashSet<employee>();
            this.medicalRecod = new HashSet<medicalRecod>();
            this.pet = new HashSet<pet>();
        }
    
        public int employeeId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int yearOfBirth { get; set; }
        public int departmentId { get; set; }
        public string jobTitle { get; set; }
        public int phoneNumber { get; set; }
        public string email { get; set; }
        public decimal salary { get; set; }
        public string userName { get; set; }
        public string Pass { get; set; }
        public string employeeStatus { get; set; }
        public Nullable<int> employeeManager { get; set; }
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoices> invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medicalRecod> medicalRecod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pet> pet { get; set; }
    }
}
