//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSouls
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceItem
    {
        public int ID { get; set; }
        public int itemCode { get; set; }
        public int invoiceNumber { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual item item { get; set; }
        public virtual invoice invoice { get; set; }
    }
}
