//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSouls
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class littleSoulsEntities1 : DbContext
    {
        public littleSoulsEntities1()
            : base("name=littleSoulsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<invoices> invoices { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<medicalRecod> medicalRecod { get; set; }
        public virtual DbSet<pet> pet { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<invoiceItems> invoiceItems { get; set; }
    }
}
