//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSouls
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class littleSoulsEntities : DbContext
    {
        public littleSoulsEntities()
            : base("name=littleSoulsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<invoiceItem> invoiceItems { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<medicalRecod> medicalRecods { get; set; }
        public virtual DbSet<pet> pets { get; set; }
        public virtual DbSet<storage> storages { get; set; }
    }
}
