//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSouls
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicalRecod
    {
        public int recordId { get; set; }
        public Nullable<int> petId { get; set; }
        public System.DateTime dateOfExamination { get; set; }
        public string treatmentsProvided { get; set; }
        public string diagnosis { get; set; }
        public string surgeryInformation { get; set; }
        public string vaccinations { get; set; }
        public int vetetinarianId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual pet pet { get; set; }
    }
}
