//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSouls
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pet()
        {
            this.medicalRecod = new HashSet<medicalRecod>();
        }
    
        public int petId { get; set; }
        public string yearOfBirth { get; set; }
        public string petSex { get; set; }
        public string petBreed { get; set; }
        public string petSpecies { get; set; }
        public string dateOfArraival { get; set; }
        public string petColor { get; set; }
        public string healthStatus { get; set; }
        public string petState { get; set; }
        public byte[] petImage { get; set; }
        public int petSetter { get; set; }
        public Nullable<int> adopter { get; set; }
        public string adoptDate { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medicalRecod> medicalRecod { get; set; }
        public virtual pet pet1 { get; set; }
        public virtual pet pet2 { get; set; }
        public virtual pet pet11 { get; set; }
        public virtual pet pet3 { get; set; }
    }
}
