//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSouls
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
        public int shipmentNo { get; set; }
        public int itemCode { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public string itemCondition { get; set; }
        public string receivedDate { get; set; }
        public string expirationDate { get; set; }
        public string supplier { get; set; }
    
        public virtual items items { get; set; }
    }
}
